const PLANS = [
  {
    id:       "etudiant",
    label:    "Étudiant",
    price:    "5,99",
    priceInt: 599,
    // ✅ Nettoyé : Uniquement l'ID Stripe, sans texte de log ni codes couleurs
    priceId:  "price_1TErCoH7DqnrXksXHnAK60pb",
    sub:      "Examens, concours, formations",
    note:     "Justificatif étudiant requis",
    features: [
      "10 analyses vocales / mois",
      "3 simulations / mois",
      "100 sujets d'entraînement",
      "4 analyses de discours / mois",
      "5 cas pratiques juridiques / mois",
      "Plaidoirie juridique — Thémis",
      "Historique 30 jours",
    ],
    excluded: ["Analyses illimitées", "Export PDF", "Accès API"],
    popular:  false,
  },
  {
    id:       "basique",
    label:    "Basique",
    price:    "9,99",
    priceInt: 999,
    // ✅ Nettoyé
    priceId:  "price_1TErCpH7DqnrXksX2ztfxJUU",
    sub:      "Professionnels en développement",
    note:     null,
    features: [
      "Analyses vocales illimitées",
      "Simulations illimitées",
      "500 sujets d'entraînement",
      "Analyses de discours illimitées",
      "20 cas pratiques juridiques / mois",
      "Plaidoirie juridique — Thémis",
      "Export PDF des plaidoiries",
      "Historique complet",
    ],
    excluded: ["Accès API", "Multi-utilisateurs", "Support dédié"],
    popular:  true,
  },
  {
    id:       "entreprise",
    label:    "Entreprise",
    price:    "19,99",
    priceInt: 1999,
    // ✅ Nettoyé
    priceId:  "price_1TErCqH7DqnrXksXJcW5LXNR",
    sub:      "Cabinets, équipes, grandes écoles",
    note:     "Facturation annuelle : 2 mois offerts",
    features: [
      "Tout l'offre Basique",
      "Cas pratiques juridiques illimités",
      "Accès API complet",
      "Tableau de bord équipe",
      "Gestion multi-utilisateurs",
      "Intégration PISTE / Légifrance",
      "Rapports de progression équipe",
      "Support prioritaire 24h",
      "Formation onboarding incluse",
    ],
    excluded: [],
    popular:  false,
  },
]